# Hi there 👋

<!--
**purplewe/purplewe** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->

- 🌱 My interest lies in APM, MicroService Monitor.

- 🚶 I’m also currently working on open source projects, say, skywalking & dolphinscheduler.

- ⚡️ Technologies I work with: Java, Golang, React and more

![Jared Tan's github stats](https://github-readme-stats.vercel.app/api?username=purplewe&show_icons=true&hide_border=false&title_color=5bd1d7&icon_color=eaffd0&text_color=f2f4f6&bg_color=263859)
